[package]
name = "steam-input-lease-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme = "../../README.md"

[[bin]]
name = "steam-input-lease"
path = "src/main.rs"
doc = false

[dependencies]
steam-input-lease.workspace = true
