[package]
name = "steam-input-lease-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme = "../../README.md"

[lib]
name = "steam_input_lease_ffi"
crate-type = ["cdylib"]

[dependencies]
steam-input-lease.workspace = true

